version: '3.9'
services:
  app:
    image: python:3.10.6-alpine3.16
    build: app/
    ports:
      - 8080:8080
    volumes:
      - './app:/app'
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: db
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

